---
- name: (2) setup-Debian.yml | Create keyring directory if not exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: (2) setup-Debian.yml | Adding MariaDB GPG key
  get_url:
    url: https://supplychain.mariadb.com/mariadb-keyring-2019.gpg
    dest: /etc/apt/keyrings/MariaDB.gpg
    mode: '0755'
    force: true

- name: (2) setup-Debian.yml | Adding mariadb.sources
  template:
    src: mariadb.sources.j2
    dest:  /etc/apt/sources.list.d/mariadb.sources
    owner: root
    group: root
    mode: 0644

- name: (2) setup-Debian.yml | Installing MariaDB
  apt:
    name: mariadb-server
    update_cache: true
    autoremove: true
    autoclean: true
    install-recommends: false
    state: latest
    policy_rc_d: 101

- name: (2) setup-Debian.yml | Installing MySQL-python
  apt:
    name: python-mysqldb
    update_cache: true
    autoremove: true
    autoclean: true
    install-recommends: false
    state: latest