---
- name: (3) configure.yml | Modifying my.cnf
  template:
    src: my.cnf.j2
    dest:  /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb

- name: (3) configure.yml | Flush handlers
  meta: flush_handlers