---
- name: (4) secure-installation.yml | Removing anonymous users
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    check_implicit_admin: true
    login_unix_socket: /run/mysqld/mysqld.sock

- name: (4) secure-installation.yml | Removing 'mysql' users
  mysql_user:
    name: mysql
    host_all: true
    state: absent
    login_user: root
    check_implicit_admin: true
    login_unix_socket: /run/mysqld/mysqld.sock

- name: (4) secure-installation.yml | Removing test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    check_implicit_admin: true
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Reload privilege tables
  command: 'mysql -ne FLUSH PRIVILEGES'
  login_user: root
  check_implicit_admin: true
  login_unix_socket: /run/mysqld/mysqld.sock
