---
- name: (4) secure-installation.yml | Removing anonymous users
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
  no_log: true

- name: (4) secure-installation.yml | Removing 'mysql' users
  mysql_user:
    name: mysql
    host_all: true
    state: absent
    login_user: root
    login_password: '{{ mysql_root_password }}'
  no_log: true