---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:

    - name: Converge | Install Python if not already present.
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-apt)
      changed_when: false

    - name: Converge | Gather facts after Python is definitely present.
      setup:

  roles:
    - ubzyhd.mariadb